[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build]
  publish = "dist/expenses_frontend/browser"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"